### ISSUE TITLE
Sentiment Analysys - Crash

### ISSUE THREAD

**Issue by JTrotta** [bhrnjica/anndotnet#52]
Find below the crash screenshot after loading SentimentAnalysys.zip  example. It appears clicking RUN.
I'm using ANNdotNET v1.2-rc20191602

![image](https://user-images.githubusercontent.com/2145654/53575772-8ed2c900-3b72-11e9-993c-af4f5317f847.png)

**Comment by bhrnjica** [comment]
Thank you for the crash report. 

Seems the machine you are trying to run the example doesn't support GPU. 
In this case, you need to change the Learner from Adam to MomentumSGD in order to successfully run the example.

Please reply on this thread in case this is not the case. 

![2019-02-28_18-07-03](https://user-images.githubusercontent.com/1240016/53584417-ceee7780-3b83-11e9-9967-682e79792ab3.png)

**Comment by JTrotta** [comment]
yes it works.
My notebook has no GPU
